Adding JSON Plugin
iainbrighton/PScribo pull request #122
Opened 2022-12-06 20:59 UTC by carceneaux

* Added JSON plugin files
* Added JSON plugin tests
* Added JSON plugin help documentation
* Updated README with JSON plugin example info

I debugged/tested the JSON plugin using several of the example scripts in the project as well as using several reports from the [AsBuiltReport](https://github.com/AsBuiltReport) framework which leverages PScribo.

The purpose of this plugin is to be able to take already existing scripts using PScribo and provide the output in a method that can be ingested by a 3rd party tool. To that end, JSON seemed to be a pretty clear answer as PowerShell can natively do this.

2022-12-06 21:41 UTC, carceneaux commented
Resolved all AppVeyor errors with the exception of one (shown below) as it related to a file not modified in this PR.

![CleanShot 2022-12-06 at 16 38 08](https://user-images.githubusercontent.com/17179966/206028708-4df7cc0b-eb1b-4025-b735-9f43b373e231.png)

I further investigated and it appears to be a newly added rule which is why it didn't pop up before.

2022-12-06 21:49 UTC, carceneaux commented
Confirmed. New rule added 2 months ago in the latest PSScriptAnalyzer [release](https://github.com/PowerShell/PSScriptAnalyzer/releases).

![CleanShot 2022-12-06 at 16 48 53](https://user-images.githubusercontent.com/17179966/206030429-0206c4c8-4dfc-4d67-949d-7dbe976d726d.png)

2022-12-07 13:49 UTC, carceneaux commented
Created a new [issue](https://github.com/iainbrighton/PScribo/issues/123) for this behavior and applied a workaround to patch the issue for now.

2022-12-15 22:12 UTC, carceneaux commented
@iainbrighton Thoughts on this?

2023-01-18 17:17 UTC, iainbrighton requested changes
You seem to have a good grasp of how the plugin architecture works and, as long as you are happy with the Json structure, it looks pretty good to me. There are only couple of minor comments that may or may not need addressing. Good job!👍

2023-01-20 18:41 UTC, carceneaux commented on appveyor.yml
> +    - ps: Install-Module -Name PSake, VirtualEngine.Build -Scope CurrentUser -Force -AllowClobber -Verbose
Change reverted.

2023-01-20 19:06 UTC, carceneaux commented on Tests/Plugins/Json/Out-JsonTable.Tests.ps1
> +        $isNix = (($PSVersionTable['PSEdition'] -eq 'Core') -and (-not $IsWindows))
Good call out. I investigated this comparing unit test results from PowerShell (5.1.17763.2931) running on Windows and PowerShell Core (7.3.0) running on MacOS and found no differences. As such, I've removed the unnecessary check.

2023-01-20 19:07 UTC, carceneaux commented
@iainbrighton Everything should now be good to go. Only failure in the build can be ignored as it's being resolved in #125.

Thanks for your time reviewing this! 😄

2023-03-16 13:28 UTC, carceneaux commented
@iainbrighton Any further requests on this? Are we good to merge?

2023-06-20 15:45 UTC, carceneaux commented
@iainbrighton Howdy! 😄 I just updated this PR to include the recent merges into the dev branch.

Any chance this PR can be merged?

2023-06-21 15:57 UTC, iainbrighton commented
> Any chance this PR can be merged?

@carceneaux If it's merged in its current form, there will be no support for the new `List` functionality. Do you plan on adding this functionality?

Thanks, Iain

2023-06-21 16:01 UTC, iainbrighton approved these changes

2023-06-21 16:07 UTC, carceneaux commented
Thanks, Iain! I'll create an issue for the new list functionality and test/add support for it.

2023-06-21 19:50 UTC, merged